# -*- coding: utf-8 -*-
#
# @file: smriti_retail_os/negative_stock/service/explain_service.py
# @description: KGF Explainability Generator service for SMRITI Negative Stock Management.
# @author: Jawahar R Mallah <jawahar.mallah@gmail.com>
# @date: 2026-06-29
# @version: 1.9.0
# @license: GPL-3.0-only
# SPDX-License-Identifier: GPL-3.0-only
# * Copyright (c) 2026 AITDL NETWORK & ERPNbook.com. All rights reserved.
#

import frappe
from frappe.utils import today

class SMRITINegativeStockExplainService(object):
	"""
	Implements Rule 10 / Rule 13 Explainability.
	Generates a dynamic human-readable audit explanation block for Case logs.
	"""

	def __init__(self, case_doc):
		self.case_doc = case_doc

	def generate_explanation(self):
		"""
		Compiles structured telemetry into a rich narrative explaining the negative stock event.
		"""
		policy_name = self.case_doc.matched_policy or "None"
		scope = self.case_doc.matched_scope or "Global"
		decision = self.case_doc.decision or "Block"
		actual_qty = frappe.db.get_value("Bin", {
			"item_code": self.case_doc.item_code,
			"warehouse": self.case_doc.warehouse
		}, "actual_qty") or 0.0

		p_doc = None
		if self.case_doc.matched_policy:
			p_doc = frappe.get_doc("SMRITI Negative Stock Policy", self.case_doc.matched_policy)

		# A. Business Meaning
		meaning = f"The system tracked a transaction requesting to sell or consume {abs(self.case_doc.negative_qty)} unit(s) of Item '{self.case_doc.item_code}' from Warehouse '{self.case_doc.warehouse}', exceeding the current physical stock balance of {actual_qty}."

		# B. Formula
		formula = "Stock Exposure = |Current Balance + Transaction Qty| where Current Balance < Transaction Qty"

		# C. Worked Example
		example = f"Worked Example:\n  Current Balance = {actual_qty}\n  Requested Deduction = {abs(self.case_doc.negative_qty)}\n  Exposure = |{actual_qty} - {abs(self.case_doc.negative_qty)}| = {abs(self.case_doc.negative_qty) - actual_qty if actual_qty > 0 else abs(self.case_doc.negative_qty)} unit(s)"

		# D. Matched Policy details
		policy_detail = f"Matched Policy Rule:\n  Policy Name: {policy_name}\n  Scope Level: {scope}\n  Decision Applied: {decision}\n  Priority Level: {p_doc.priority if p_doc else 0}"

		# E. Recommendations & Alternatives
		alternatives_str = self.get_alternatives_explanation()

		explanation = f"""### SMRITI NEGATIVE STOCK EXCEPTION TRACE LOG
(Constitutional Rule 10 & 13 Traceability Standard)

**1. Business Context & Metrics:**
{meaning}

**2. Formula & Assessment:**
* **Formula:** `{formula}`
* {example}

**3. Policy Resolution:**
{policy_detail}

**4. Alternatives & Recovery:**
{alternatives_str}

---
*Generated by: SMRITI Knowledge Graph & Explainability Hub (KGF)*
*Author Profile: Jawahar R. Mallah, Founder & Chief Architect, AITDL*
*Document Version: 1.9.0*
"""
		return explanation

	def get_alternatives_explanation(self):
		"""
		Suggests alternative actions (e.g., PSV alternative warehouses).
		"""
		item_group = frappe.db.get_value("Item", self.case_doc.item_code, "item_group")
		
		# Find other warehouses with stock of this item
		other_stocks = frappe.get_all("Bin", filters={
			"item_code": self.case_doc.item_code,
			"warehouse": ["!=", self.case_doc.warehouse],
			"actual_qty": [">", 0]
		}, fields=["warehouse", "actual_qty"], limit=3)

		if other_stocks:
			alts = "\n".join([f"  - Warehouse '{x.warehouse}': Balance {x.actual_qty} units" for x in other_stocks])
			return f"Alternative stock availability found in surrounding warehouses:\n{alts}\n\nRecommended Action: Initiate a Material Transfer to replenish."
		else:
			return "No alternative local stock was found in surrounding warehouses.\nReplenishment via Purchase Order or Stock Reconciliation is required."
